Fix/updated vda login
verida/verida-vue-components pull request #30
Opened 2022-02-10 17:07 UTC by cmcWebCode40

- Updated profile event listener
- FIxes minor issue with avatar display

2022-02-15 00:37 UTC, nick-verida requested changes
A few minor changes

2022-02-15 00:37 UTC, nick-verida commented on components/account/src/lib-components/vda-account.vue
> +        // this.profile = this.$VeridaHelper.profile;
remove commented out code

2022-02-15 00:37 UTC, nick-verida commented on lerna-debug.log
> +36 error Error: Command failed with exit code 128: git tag @verida/vue-account@0.1.3 -m @verida/vue-account@0.1.3
Remove this file

2022-02-15 00:37 UTC, nick-verida commented on package.json
> +		"test:unit": "vue-cli-service test:unit --env=./tests/custom-test-env.js",
This file doesn't seem to be in the commit

2022-02-22 07:59 UTC, cmcWebCode40 commented
@nick this PR has been updated with :

- [ ]  Requested changes
- [ ] Refactor to remove vuex store
- [ ] separation of concerns in vda components
- [ ] test setup

FYI: the test scripts fail ATM the moment issue can be found here https://github.com/verida/verida-vue-components/issues/29#issuecomment-1039524603

but this PR can be merged because it's currently a blocker for https://github.com/verida/demo-credential-issuer/pull/38

2022-02-23 01:09 UTC, nick-verida approved these changes
Made a change to fix the TextEncoder issue

2022-02-23 01:11 UTC, merged