feat: truncate did and fix style issue
verida/verida-vue-components pull request #91
Opened 2023-01-23 11:00 UTC by cmcWebCode40

- Added functionality to truncate did from `did:vda:testnet:0x2b160b311106de4a899B5AD3D934ADD9c8516Add` to  `did:vda:0x2449..`
- Fix CSS styles issue 

closes #88

2023-01-25 03:45 UTC, aurelticot requested changes

2023-01-25 03:45 UTC, aurelticot commented on components/account/src/lib-components/vda-account.vue
> +    /** method to remove the "testnet" part in the did and trucate into e.g "did:vda:0x2449.."  format */
My understanding was the purpose was not to hide testnet from the DID method.

Using `split(":")` is ok but the goal is to extract the whole did method (several elements separated by ":") from actual key (the last item from the split array).
Is then to truncate the key only.

2023-01-25 03:45 UTC, aurelticot commented on components/account/src/lib-components/vda-account.vue
>        this.isCopied = true;
`navigator.clipboard` can be undefined, so the value may not be copied.

2023-01-25 04:48 UTC, cmcWebCode40 commented on components/account/src/lib-components/vda-account.vue
> +    /** method to remove the "testnet" part in the did and trucate into e.g "did:vda:0x2449.."  format */
do you mean I should truncate only the last item from the split array ?

eg. `did:vda:testnet:0xC64...` ?

2023-01-26 02:59 UTC, aurelticot commented on components/account/src/lib-components/vda-account.vue
> +    /** method to remove the "testnet" part in the did and trucate into e.g "did:vda:0x2449.."  format */
Yes

2023-01-26 03:33 UTC, cmcWebCode40 commented on components/account/src/lib-components/vda-account.vue
>        this.isCopied = true;
would you suggest I revert to using the previous copyToClipoboard library or handle when its undefined ?

2023-01-27 00:34 UTC, aurelticot commented on components/account/src/lib-components/vda-account.vue
>        this.isCopied = true;
I think it's a feature we don't need a library for, but then, our code must be robust implementing it.

The main question is, should you handle it in this unrelated PR or in a dedicated one?
(And should you have started it in this unrelated PR in the first place?)

2023-01-27 04:33 UTC, cmcWebCode40 commented on components/account/src/lib-components/vda-account.vue
>        this.isCopied = true;
ok, i think I will have to open a different ticket to implement that feature

2023-01-27 08:24 UTC, cmcWebCode40 commented on components/account/src/lib-components/vda-account.vue
> +    /** method to remove the "testnet" part in the did and trucate into e.g "did:vda:0x2449.."  format */
fixed

2023-01-27 08:24 UTC, cmcWebCode40 commented on components/account/src/lib-components/vda-account.vue
>        this.isCopied = true;
changes revert will fixed on its ticket

2023-01-27 08:26 UTC, cmcWebCode40 commented on components/account/src/lib-components/vda-login.vue
> +  animation: loader-icon 0.8s linear infinite alternate;
fixed

2023-01-27 09:26 UTC, aurelticot approved these changes

2023-01-27 10:07 UTC, merged